#!/bin/bash -ex
set -eu -o pipefail

find_latest_neovim_version()
{
    git ls-remote --tags git://github.com/neovim/neovim.git \
        | grep -oh 'v[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}' \
        | sort --version-sort -r \
        | head -n 1
}

VERSION=$(find_latest_neovim_version)
curl -sSLO "https://github.com/neovim/neovim/releases/download/${VERSION}/nvim-linux64.tar.gz"

tar xfz nvim-linux64.tar.gz >/dev/null

mv nvim-linux64/bin .
mv nvim-linux64/share .
rm -rf nvim-linux64*

# install python3 provider module
python3 -m pip install --user --upgrade pynvim

# crete the directory structure and link files
mkdir -p ~/.config/nvim/
dotlink -o "$PWD/data/init.vim" ~/.config/nvim/init.vim

mkdir -p ~/.local/share/nvim/site/autoload/

# install plug
curl -fsSLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
