#!/bin/bash -ex
set -eu -o pipefail

git clone --depth 1 https://github.com/radare/radare2.git
cd radare2/
./configure --prefix=$(dirname $PWD)
make -j $(nproc)
make install
cd ..

cd bin
for i in ???*
do
    mv $i $i.real
    cat <<END > $i
#!/bin/bash
LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$PWD/../lib $PWD/$i.real "\$@"
END
    chmod 755 $i
done
cd ..

# link the rc file
ln -sf $PWD/data/radare2rc ~/.radare2rc

PIP_VENV=ctftools manage pip install -U r2pipe
