#!/bin/sh -e

# wrapper for a scriptable apt-get.

export DEBIAN_FRONTEND=noninteractive

# update the package list
apt-get -q update

# install the packages
apt-get install -q -y --auto-remove "$@"

# remove package lists and apt-get metadata. Reduce the size of the
# docker image layer.
apt-get -q clean
rm -rf /var/lib/apt/lists/*
