#!/bin/bash -ex
set -eu -o pipefail

function find_latest_tmux_release()
{
    curl --silent "https://api.github.com/repos/tmux/tmux/releases/latest" \
        | grep '"tag_name"' \
        | sed -E 's/.*"([^"]+)".*/\1/'
}

VERSION=$(find_latest_tmux_release)
curl -fsSLO "https://github.com/tmux/tmux/releases/download/$VERSION/tmux-${VERSION}.tar.gz"

tar xzf "tmux-${VERSION}.tar.gz"
rm -f "tmux-${VERSION}.tar.gz"

cd "tmux-$VERSION"
./configure --prefix="$OLDPWD/" CPPFLAGS="-P"
make
make install

cd ..
rm -rf "tmux-${VERSION}"

dotlink -o $PWD/data/tmux.conf ~/.tmux.conf
